[package]
name = "cbasm"
version = "0.1.1"
edition = "2021"
description = "Asm assembler & dissasembler for cbvm bytecode"
license = "GGPL"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbvm = "0.5.8"
